### ISSUE TITLE
Shared Element Transitions not working (v24.2.1-rc1)

### ISSUE THREAD

**Issue by dlmcdonald** [xamarin/AndroidSupportComponents#16]
### Xamarin.Android Version (eg: 6.0):

7.0.1.3
### Operating System & Version (eg: Mac OSX 10.11):

Windows 10
### Support Libraries Version (eg: 23.3.0):

v24.2.1-rc1
### Describe your Issue:

I updated to the alpha nuget package to test out the DiffUtils when I noticed that my shared transition elements were not animating any more. This was still working on the stable package. I understand that this is obviously still in alpha, but I just wanted to check if you were aware of the issue
### Steps to Reproduce (with link to sample solution if possible):

I just used a very basic empty sample with the following code to navigate from one activity to the second activity: 
`Pair participant = new Pair(imgImage, ViewCompat.GetTransitionName(imgImage));`
`var opts = ActivityOptionsCompat.MakeSceneTransitionAnimation(this, participant);`
`Intent detailsIntent = new Intent(this, typeof(SecondActivity));`
`StartActivity(detailsIntent, opts.ToBundle());`

**Comment by jasonctoms** [comment]
I believe this issue still exists in the stable release of 24.2.1.  See my StackOverflow question [here.](http://stackoverflow.com/questions/40995560/why-has-my-shared-element-transition-stopped-working)

**Comment by Redth** [comment]
I've been able to reproduce this locally now.  I'm going to have to do some digging to see why it would work on java but not in our bindings, this is something that we don't usually see (where the behaviour is different from the binding to the java usage)...

**Comment by Redth** [comment]
@jasonctoms @dlmcdonald I can't reproduce it working on 23.3.0 stable version.  Do either of you have a known working example of this on an older package version?

**Comment by jasonctoms** [comment]
@redth I cannot post a full project because the code is for work and not open source. But the snippet in my stack overflow post is a pretty normal shared element transition. Pressing on a webview launching an intent to an activity that is just a full screen webview. On 23.3.0 the webview properly expanded to fill the screen. But now it just looks like a normal activity transition, with the full screen changing. I have confirmed in debugging that the shared element options code is being executed, it just doesn't seem to have any effect.

**Comment by Redth** [comment]
I'm using a simple example of transitioning from a smaller ImageView to a bigger one on the second activity.  In my java app it works fine, on Xamarin it does not, not even with 23.3.0 which is why I ask for a 'working' example since I can't reproduce it _ever_ working.

**Comment by dlmcdonald** [comment]
@Redth I have an example project that I initially used to test this. I can also confirm that it does not work using 23.3.0, however, using 23.4.0.1, it does definitely work. If you are unable to get it to work using that version of the library, let me know and I can send you my working example

**Comment by jasonctoms** [comment]
@Redth I am sorry I was mistaken.  I had previously been using 23.4.0.1 when it worked too, not 23.3.0.

**Comment by csdinon** [comment]
possibly related to this bug? https://bugzilla.xamarin.com/show_bug.cgi?id=40527
This looks to be caused by ActivityOptionsCompat.ToBundle() returning null.

**Comment by Redth** [comment]
This should be working in 25.3.1-beta1, I can no longer reproduce the issue with this version.

**Comment by mattleibow** [comment]
@Redth I think this is still an issue :( Hopefully I am doing something wrong, but this is what I have so far.

This is the C# code: https://github.com/mattleibow/SharedElementTransitions
This is the Java code: https://github.com/obaro/SharedElementTransitions

I think I coped the code exactly (almost), but the transitions are not working at all. I am using the v25.4.0.1 packages.

**Comment by mattleibow** [comment]
I just wanted to leave a comment. For some reason, this works totally fine when the `minSdkVersion` is set to API 14+ (v4.0+). As soon as I drop it, nothing works...
